---
# file: roles/docker-dna_percona/tasks/grants.yml

- name: Add Docker database user 
  mysql_user: user={{ galera['dbusers']['docker']['username'] }} host={{ galera['dbusers']['docker']['host'] }}  password={{ galera['dbusers']['docker']['password'] }} priv=*.*:"all privileges"

- name: Add xtrabackup database user (for Galera SST)
  mysql_user: user={{ galera['dbusers']['xtrabackup']['username'] }} host="localhost" password={{ galera['dbusers']['xtrabackup']['password'] }} priv=*.*:"grant, reload, replication client"

- name: Add clustercheck database user (for clustercheck/xinetd -> haproxy) 
  mysql_user: user={{ galera['dbusers']['clustercheck']['username'] }} host="localhost" password={{ galera['dbusers']['clustercheck']['password'] }} priv=*.*:"grant, reload, replication client"

