---
# file: roles/docker-dna_percona/tasks/grants.yml

- name: Add Docker database user 
  mysql_user: user={{ docker_username }} host={{ docker_host }}  password={{ docker_password }} priv=*.*:"all privileges"

- name: Add xtrabackup database user (for Galera SST)
  mysql_user: user={{ xtrabackup_username }} host="localhost" password={{ xtrabackup_password }} priv=*.*:"grant, reload, replication client"

- name: Add clustercheck database user (for clustercheck/xinetd -> haproxy) 
  mysql_user: user={{ clustercheck_username }} host="localhost" password={{ clustercheck_password }} priv=*.*:"grant, reload, replication client"
